version: 2 # use CircleCI 2.0
    jobs: # a collection of steps
      build: 
        working_directory: ~/goof # directory where steps will run
        docker: # run the steps with Docker
          - image: circleci/node # ...with this image as the primary container; this is where all `steps` will run
        steps: # a collection of executable commands
          - checkout # special step to check out source code to working directory
          - run:
              name: update-npm
              command: 'sudo npm install -g npm@latest'
          - run:
              name: install-snyk
              command: 'sudo npm install -g snyk'     
          - run: # installs json to html mapper
              name: install-snyk-to-html
              command: 'sudo npm install -g snyk-to-html'
          - run: # run snyk auth - authenticate snyk use environment variables to add token
              name: snyk auth
              command: snyk auth d24f029b-f3c4-4adc-853c-12d622ed1faf
          - run: # run snyk monitor
              name: snyk monitor
              command: snyk monitor
          - run: # output to HTML
              name: snyk test to HTML
              command: snyk test --json | snyk-to-html -o results.html
          - store_artifacts:
              path: results.html
              destination: results.html